### ISSUE TITLE
explain fig 5 in the paper

### ISSUE THREAD

**Issue by demon-ling** [ddehun/DEnsity#1]
Can you explain what the x-axis and y-axis of Figure 5 represent in the paper？thank you!
![image](https://github.com/ddehun/DEnsity/assets/69795280/494b6934-9e4b-4bbd-bd60-06df29a328ad)

**Comment by ddehun** [comment]
Hi, @demon-ling. Thank you for your interest in our work!

The x-axis and y-axis denote the metric score (in Eq. 3) and the number of responses in each bin, respectively.
